#:include Base.kv

<Login>:
    MDLabel:
        text: 'Login Screen'
        halign: 'center'
        theme_text_color: 'Primary'
        font_style: 'H5'
    MDTextField:
        hint_text: 'Username'
        pos_hint: {'center_x': 0.5, 'center_y': 0.6}
        size_hint_x: None
        width: 200
    MDTextField:
        hint_text: 'Password'
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        size_hint_x: None
        width: 200
    Base:
        id: base_screen

